### ISSUE TITLE
PDF button in the main page of paper details activity is broken.

### ISSUE THREAD

**Issue by arindas** [dcalano/Synapse#1]
The PDF button is supposed to open a link to the specified document which can be downloaded by a browser. Instead it returns a text response containing the file URL, which the the system prompts the user to share as text or save as a document  on google drive, which doesn't satisfy the intended purpose.

**Comment by dcalano** [comment]
Issue has been fixed and update released.

https://github.com/dcalano/Synapse/commit/919bcbbe1916ff54df7874098b0647196adc21d1#diff-7bd2b2389f72b1351637f1d0f45f42bf
